import img1 from '../../../../assets/Photos/announcements/5.png'

export const SubpageData = [
    {
        label: 'ANNOUNCEMENT',
        title: 'Study Mission Abroad The RV Kasarinlan',
        susbtitle: 'By Grig C. Montegrande',
        img: img1,
        whiteBgText: 'The RV Kasarinlan, the first research vessel owned by the University of the Philippines Marine Science Institute, leaves the Port of Manila with an all-Filipino crew of 74 mostly young scientists for a two-week study of the West Philippine Sea off the Philippine-claimed Kalayaan Island Group.',
        p1: 'For two weeks, the 74-member team led by the University of the Philippines Marine Science Institute (UP MSI) will engage in a scientific expedition called "Protect WPS," or Predicting Responses between Ocean Transport and Ecological Connectivity of Threatened ecosystems in the West Philippine Sea.',
        p2: 'For chief scientist Deo Florence Onda, the expedition, while yet to be completed, is already a triumph for both the country and its youth. "This is a big leap for Filipinos, for the appreciation of science," said the 31-year-old Onda, the youngest faculty member in the country national institute for marine science studies.',
        p3: 'Kasarinlans science crew consisted of mostly millennials, with the youngest researcher at 21. Most of them were graduate students of marine science, working in various oceanography and ecology laboratories, who stepped up to offer their services for the study. A majority of the young researchers were women. According to Onda, the study aims to look into the "connectivity" of the ecosystems in the West Philippine Sea.',
        p4: 'The study is being conducted in partnership with the Biodiversity Management Bureau of the Department of Environment and Natural Resources and the Bureau of Fisheries and Aquatic Resources of the Department of Agriculture-Biodiversity thriving in the Kalayaan Island Group has significant impact on mainland Luzon and Palawan province, said UP MSI director Fernando Siringan, citing data from the past two decades.Since this connection has been seen only in certain organisms, the expedition intends to expand the sample and strengthen the link.',
        p5: '"For instance, the fish eggs from the Kalayaan Island Group are being brought by the ocean current to the mainland ... so there is a connection between the systems in Kalayaan and West Palawan," Onda said. "So this has an implication on our fisheries. "Their research can also form part of the scientific knowledge needed if the country is to declare the Kalayaan Island Group a marine protected area, an idea that has been recently floated by the government in light of territorial claims in the waters.',
        p6: 'For UP MSI, Kasarinlan is a victory on its own: It is the institutes first own research vessel after nearly 50 years."Kasarinlan means sovereignty It is good to be able to do science on your own and as a Filipino, it is good to do it all-Filipino: with funding from Filipino taxpayers, [a vessel] manned by a Filipino crew and scientific cruises conducted by Filipino scientists," Siringan said. "You are expressing freedom and sovereignty by doing it at any waters of the  Philippines," he added.',
        p7: 'Despite the threat posed by Chinese vessels in the disputed area, the team remained confident that it had assessed the situation so it can conduct research safely. "We have been doing our research there for so many years," Onda said. "All had been considered and factored in." Jitters and tensions aside, for Aldwyn Calaguing, the teams vounqest member, he sees the opportunity to sail and study the Philippine seas as a great privilege.',
        p8: '"This is the pinnacle of my dream," he said, as he shared how he had prepared to dive and study seagrass, as a research assistant in the phycology (study of algae) laboratory. "This is my training ground and I can only hope to Inspire. "',
    }
]